[project]
name = "mini-agent"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "VingerChan", email = "2741232639@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
mini-agent = "mini_agent:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
